version: 2.1
commands:
  run-mtest:
    description: "multi-host test"
    parameters:
      suite:
        type: string
      target:
        type: string
        default: ""
    steps:
      - run:
          name: Store Service Account
          command: |
            echo $GCLOUD_SERVICE_ACCOUNT > account.json
            gcloud auth activate-service-account --key-file=account.json
      - run:
          command: |
            ./bin/run-mtest.sh <<parameters.suite>> <<parameters.target>>

jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.12-bionic
      - image: quay.io/coreos/etcd:v3.3
    steps:
      - checkout
      - run: make build
      - run:
          command: |
            ./sabakan -dhcp-bind 0.0.0.0:10067 \
                      -etcd-endpoints http://localhost:2379 \
                      -advertise-url http://localhost:10080
          background: true
      # make test on CircleCI runs e2e test at once.
      - run: make test
      - run:
          command: |
            mkdir /tmp/workspace
            cp ./sabakan ./sabactl /tmp/workspace
      - run: cp LICENSE /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - sabakan
            - sabactl
            - LICENSE
  build-image:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Copy binaries
          command: |
            cp /tmp/workspace/sabakan docker
            cp /tmp/workspace/sabactl docker
            cp /tmp/workspace/LICENSE docker
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker build -t quay.io/cybozu/sabakan:latest ./docker
      - run:
          name: Save image
          command: |
            mkdir -p /tmp/docker
            docker save quay.io/cybozu/sabakan:latest -o /tmp/docker/image
      - persist_to_workspace:
          root: /tmp/docker
          paths:
            - image
  push-image:
    docker:
      - image: docker:stable
    steps:
      - attach_workspace:
          at: /tmp/docker
      - setup_remote_docker
      - run: docker load -i /tmp/docker/image
      - run:
          name: Push docker image to Quay.io
          command: |
            docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
            echo "pushing sabakan image ..."
            TAG=$(echo $CIRCLE_TAG | cut -c 2-)
            docker tag quay.io/cybozu/sabakan:latest quay.io/cybozu/sabakan:$TAG
            docker push quay.io/cybozu/sabakan:$TAG
            BRANCH=$(echo $TAG | cut -d "." -f 1-2)
            docker tag quay.io/cybozu/sabakan:latest quay.io/cybozu/sabakan:$BRANCH
            docker push quay.io/cybozu/sabakan:$BRANCH
  mtest:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run-mtest:
          suite: ./functions

workflows:
  version: 2
  main:
    jobs:
      - build
      - build-image:
          requires:
            - build
      - mtest
  release:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - build-image:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - push-image:
          requires:
            - build-image
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
