version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.12-bionic
      - image: quay.io/coreos/etcd:v3.3
    steps:
      - checkout
      - run: make build
      - run:
          command: |
            ./sabakan -dhcp-bind 0.0.0.0:10067 \
                      -etcd-endpoints http://localhost:2379 \
                      -advertise-url http://localhost:10080
          background: true
      # make test on CircleCI runs e2e test at once.
      - run: make test
  build-image:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            docker build -t quay.io/cybozu/sabakan:latest .
      - run:
          name: Push docker image to Quay.io
          command: |
            docker login -u $QUAY_USER -p $QUAY_PASSWORD quay.io
            echo "pushing sabakan image ..."
            TAG=$(echo $CIRCLE_TAG | cut -c 2-)
            docker tag quay.io/cybozu/sabakan:latest quay.io/cybozu/sabakan:$TAG
            docker push quay.io/cybozu/sabakan:$TAG
            BRANCH=$(echo $TAG | cut -d "." -f 1-2)
            docker tag quay.io/cybozu/sabakan:latest quay.io/cybozu/sabakan:$BRANCH
            docker push quay.io/cybozu/sabakan:$BRANCH
  mtest:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run:
          name: Store Service Account
          command: |
            echo $GCLOUD_SERVICE_ACCOUNT > account.json
            gcloud auth activate-service-account --key-file=account.json
      - run: ./bin/run-mtest.sh

workflows:
  version: 2
  main:
    jobs:
      - build
      - mtest
  release:
    jobs:
      - build-image:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
